apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: django-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-env
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: django-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DJANGO_SECRET_KEY

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_NAME

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_PASSWORD

            - name: DATABASE_HOST
              value: "10.107.11.99"

            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_PORT
