# Generated by Django 5.1.6 on 2025-03-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RocketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=100)),
                ('launch_date', models.DateTimeField()),
                ('success', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
